services:
  db:
    image: pgvector/pgvector:pg16
    container_name: vertico-db
    environment:
      POSTGRES_DB: vertico
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: vertoco123
    ports:
      - "5432:5432"
    volumes:
      - vertico_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tom"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    container_name: vertico-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://tom:vertoco123@db:5432/vertico
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../:/app        # hot reload during dev

volumes:
  vertico_db_data: