import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { DiffsList } from "./DiffsList";
export function SidePane({ open, onClose, diff, diffData, context, sessions, currentSessionId, onSelectSession, onSelectDiff, apiStatus, onOpenQuickPick, tab, onTabChange: setTab, api, onIndexRepo, }) {
    const isConnected = apiStatus.toLowerCase().startsWith("connect");
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: `side-panel-backdrop ${open ? "open" : ""}`, onClick: onClose, "aria-hidden": "true" }), _jsxs("aside", { className: `side-panel ${open ? "open" : ""}`, "aria-label": "Reference Panel", children: [_jsxs("div", { className: "side-panel-header", children: [_jsx("div", { className: "side-panel-tabs", children: ["diffs", "sessions", "context"].map((t) => (_jsx("button", { onClick: () => setTab(t), className: `side-panel-tab ${tab === t ? "active" : ""}`, children: t === "diffs" ? "Diffs" : t === "sessions" ? "Sessions" : "Context" }, t))) }), _jsx("button", { onClick: onClose, className: "side-panel-close-btn", title: "Close side panel", "aria-label": "Close side panel", children: _jsx("svg", { width: "14", height: "14", viewBox: "0 0 14 14", fill: "none", children: _jsx("path", { d: "M1.5 1.5L12.5 12.5M1.5 12.5L12.5 1.5", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round" }) }) })] }), _jsxs("div", { className: "side-panel-content", children: [tab === "diffs" && (_jsx(DiffsList, { sessions: sessions, currentSessionId: currentSessionId, onSelectDiff: onSelectDiff, api: api })), tab === "sessions" && (_jsx("div", { className: "flex flex-col h-full overflow-hidden", children: _jsx("div", { className: "p-2 space-y-1 overflow-y-auto flex-1", children: sessions.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center justify-center p-8 text-center text-muted text-xs", children: [_jsx("p", { className: "font-medium text-[#f1e4d9]", children: "No sessions yet" }), _jsx("p", { className: "text-dim text-[11px] mt-1", children: "Start a chat to create a new session." })] })) : (sessions.map((s) => {
                                        const isActive = s.session_id === currentSessionId;
                                        return (_jsxs("button", { onClick: () => {
                                                onSelectSession(s);
                                                onClose();
                                            }, className: `side-panel-row ${isActive ? "active" : ""}`, title: `Switch to session ${s.filename || s.session_id}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-medium text-xs text-[#f1e4d9] truncate", children: s.filename || "untitled session" }), s.status && (_jsx("span", { className: "text-[10px] px-1.5 py-0.5 rounded bg-[#24262B] text-[var(--gold)]", children: s.status }))] }), _jsxs("div", { className: "text-[11px] text-muted truncate mt-0.5 font-mono", children: [s.session_id.slice(0, 16), "..."] })] }, s.session_id));
                                    })) }) })), tab === "context" && (_jsx("div", { className: "flex-1 overflow-hidden h-full", children: context }))] }), _jsxs("div", { className: "side-panel-footer", children: [_jsxs("div", { className: "flex items-center gap-2 text-xs", children: [_jsx("span", { className: "w-2 h-2 rounded-full inline-block shrink-0", style: {
                                            background: isConnected ? "#10b981" : "#f43f5e",
                                        } }), _jsx("span", { className: "truncate", children: `API: ${apiStatus}` })] }), _jsxs("div", { className: "flex items-center gap-2 ml-auto", children: [onIndexRepo && (_jsxs("button", { onClick: onIndexRepo, className: "text-xs text-muted hover:text-foreground flex items-center gap-1.5 transition-colors shrink-0", title: "Index repository for context (Ctrl+Shift+I)", children: [_jsxs("svg", { width: "14", height: "14", viewBox: "0 0 14 14", fill: "none", children: [_jsx("path", { d: "M7 1C10.3137 1 13 3.68629 13 7M13 7C13 10.3137 10.3137 13 7 13M1 7C1 3.68629 3.68629 1 7 1M7 1C3.68629 1 1 3.68629 1 7", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round" }), _jsx("path", { d: "M7 10L9.5 12.5M7 10L4.5 12.5M7 10L12.5 7M7 10L1.5 7", stroke: "currentColor", strokeWidth: "1.5", strokeLinecap: "round" })] }), _jsx("span", { children: "Index Repo" })] })), _jsxs("button", { onClick: () => {
                                            onClose();
                                            onOpenQuickPick();
                                        }, className: "text-xs text-muted hover:text-foreground flex items-center gap-1.5 transition-colors shrink-0 ml-2", title: "Recent sessions quick-pick (Cmd/Ctrl+K)", children: [_jsx("span", { children: "Quick Pick" }), _jsx("kbd", { className: "bg-[#24262B] px-1.5 py-0.5 rounded text-[10px] text-[var(--gold)]", children: "\u2318K" })] })] })] })] })] }));
}
